services:
  - type: web
    name: computer-shop-backend
    env: python
    region: oregon
    buildCommand: bash build.sh
    startCommand: cd computer_shop_backend && gunicorn computer_shop_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: computer-shop-db
          property: connectionString